---
title: "SQL demonstration"
output: html_document
date: "2023-03-17"
---

```{r setup, include=FALSE}
library(odbc)
library(DBI)
library(tidyverse)
library(RSQLite)
game_sales_data = read.csv("C:\\Users\\tommy\\桌面\\New folder\\game_sales_data.csv")
reviews = read.csv("C:\\Users\\tommy\\桌面\\New folder\\reviews.csv")

con <- dbConnect(drv = RSQLite::SQLite(),
                 dbname = ":memory:")

#store sample data in database
dbWriteTable(conn = con, 
             name = "game_sales",
             value = game_sales_data)
dbWriteTable(conn = con, 
             name = "reviews",
             value = reviews)
#remove the local data from the environment
rm(reviews, game_sales_data)
```

SQL functions are executed in this R markdown file. In the following demonstrations, I will investigate video game sales over the years. The data is from Kaggle, which contains 19,601 video games' sales, reviews, publisher, etc. in two separate tables- "game_sales" and "reviews".

This is a preview of the two tables in the SQL database

```{R}
tbl(src = con, "game_sales")
tbl(src = con, "reviews")
```

1. The top 10 selling video games of all time.

```{sql, connection = con, output.var= "M1_results"}
SELECT *
  FROM game_sales
ORDER BY games_sold DESC
LIMIT 10;
```
```{R, echo=FALSE}
options(width = 300)
print(M1_results)
```

2. Left join the "game_sales" and "reviews" tables, and check the number of games with no reviews.
```{sql, connection = con, output.var= "M2_results"}
SELECT COUNT(game_sales.game)
FROM game_sales
LEFT JOIN reviews ON game_sales.game = reviews.game
WHERE critic_score IS NULL AND user_score IS NULL;
```
```{R, echo=FALSE}
options(width = 300)
print(M2_results)
```
There are quite a lot of games with no reviews out of the 19601 games!

3. What is the best year of video games according to the average reviews of critics? (Result saved as "top_critic_years") 
```{sql, connection = con, output.var= "M3_results"}
CREATE VIEW top_critic_years AS 
SELECT game_sales.year, ROUND(AVG(reviews.critic_score),2) AS avg_critic_score
FROM game_sales
INNER JOIN reviews ON game_sales.game = reviews.game
GROUP BY game_sales.year
ORDER BY avg_critic_score DESC
LIMIT 10;
```
```{R, echo=FALSE}
options(width = 300)
tbl(src = con, "top_critic_years")
```
Looks like the top 3 years are all in the 90s. But still, the range of years in the top 10 is quite wide. Maybe some of these years only released very few games, which shouldn't be considered a good year for video games.

4. Setting more conditions- Only years with more than 15 game releases are taken into consideration. (Result saved as "top_critic_years_more_than_four_games") 
```{sql, connection = con, output.var= "M4_results"}
CREATE VIEW top_critic_years_more_than_four_games AS 
SELECT game_sales.year, ROUND(AVG(reviews.critic_score),2) AS avg_critic_score, COUNT(game_sales.game) AS num_games
FROM game_sales
INNER JOIN reviews ON game_sales.game = reviews.game
GROUP BY game_sales.year
HAVING COUNT(game_sales.game) > 15
ORDER BY avg_critic_score DESC
LIMIT 10;
```
```{R, echo=FALSE}
options(width = 300)
tbl(src = con, "top_critic_years_more_than_four_games")
```
Interesting that in the 2010s, many more games are released each year. Probably due to the rise of indie games.

5. What are the games that got dropped off when moving from demo 3 to 4?
```{sql, connection = con, output.var= "M5_results"}
SELECT top_critic_years.year, top_critic_years.avg_critic_score
FROM top_critic_years
EXCEPT
SELECT top_critic_years_more_than_four_games.year,top_critic_years_more_than_four_games.avg_critic_score
FROM top_critic_years_more_than_four_games
ORDER BY avg_critic_score DESC
```
```{R, echo=FALSE}
options(width = 300)
print(M5_results)
```
These two years got good critic ratings but only had fewer than 15 games released.

6. We have looked at the average critic ratings. How about the average user ratings (For years with more than 15 game releases)? (Result saved as "top_user_years_more_than_four_games") 
```{sql, connection = con, output.var= "M6_results"}
CREATE VIEW top_user_years_more_than_four_games AS 
SELECT game_sales.year, ROUND(AVG(reviews.user_score),2) AS avg_user_score, COUNT(game_sales.game) AS num_games
FROM game_sales
INNER JOIN reviews ON game_sales.game = reviews.game
GROUP BY game_sales.year
HAVING COUNT(game_sales.game) > 15
ORDER BY avg_user_score DESC
LIMIT 10;
```
```{R, echo=FALSE}
options(width = 300)
tbl(src = con, "top_user_years_more_than_four_games")
```

7. What are the years with top ranking user AND critic ratings?
```{sql, connection = con, output.var= "M7_results"}
SELECT top_critic_years_more_than_four_games.year
FROM top_critic_years_more_than_four_games
INNER JOIN top_user_years_more_than_four_games on top_critic_years_more_than_four_games.year = top_user_years_more_than_four_games.year; 
```
```{R, echo=FALSE}
options(width = 300)
print(M7_results)
```
Looks like 1990 and 1994 have games ranked high by both users and critics.

8. How much games were sold in 1990 and 1994? (This is a sub query demonstration. Sub query is needed when the previous output was not saved and therefore, cannot be called directly.)
```{sql, connection = con, output.var= "M8_results"}
SELECT g.year, SUM(g.games_sold) AS total_games_sold
FROM game_sales g
WHERE g.year IN (SELECT top_critic_years_more_than_four_games.year
FROM top_critic_years_more_than_four_games
INNER JOIN top_user_years_more_than_four_games on top_critic_years_more_than_four_games.year = top_user_years_more_than_four_games.year)
GROUP BY g.year
ORDER BY total_games_sold DESC;
```
```{R, echo=FALSE}
options(width = 300)
print(M8_results)
```



